const DEFAULT_API="https://script.google.com/macros/s/AKfycbwRXtdjZYyrKrJC8DBiRvL7AoXNYKVeMuTlygWP0tFPGIdguqzLIWaz7GESIG3vZqh7/exec";
const statuses=["تم استلام المستندات","جاري مراجعة المستندات","تم التسجيل المسبق للشحنة (ACID)","تم إنهاء الإجراءات","تم شحن السيارة","وصلت ميناء سفاجا","جاري التخليص الجمركي","تم إنهاء الفحص","تم الإفراج عن السيارة","خرجت من الميناء","تم التسليم"];
document.addEventListener("DOMContentLoaded",()=>{const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();const b=document.getElementById("menuBtn"),n=document.getElementById("mainNav");if(b&&n){b.onclick=()=>{const o=n.classList.toggle("open");b.setAttribute("aria-expanded",o)};n.querySelectorAll("a").forEach(a=>a.onclick=()=>{n.classList.remove("open");b.setAttribute("aria-expanded","false")})}initSlider();initLeadForm();const s=document.getElementById("carStatus");if(s){s.innerHTML="";statuses.forEach((x,i)=>s.add(new Option((i+1)+". "+x,i)))}const save=document.getElementById("saveCar");if(save)save.onclick=saveTrackingCar;const f=document.getElementById("trackForm");if(f)f.onsubmit=e=>{e.preventDefault();showTrack(val("trackCode"))}});
function initSlider(){const slides=[...document.querySelectorAll(".slide")],dots=[...document.querySelectorAll(".dot")];if(!slides.length)return;let i=0,t;const show=x=>{i=(x+slides.length)%slides.length;slides.forEach((s,k)=>s.classList.toggle("active",k===i));dots.forEach((d,k)=>d.classList.toggle("active",k===i))};const restart=()=>{clearInterval(t);t=setInterval(()=>show(i+1),5000)};document.getElementById("prevSlide")?.addEventListener("click",()=>{show(i-1);restart()});document.getElementById("nextSlide")?.addEventListener("click",()=>{show(i+1);restart()});dots.forEach((d,k)=>d.onclick=()=>{show(k);restart()});restart()}
function initLeadForm(){const f=document.getElementById("leadForm");if(!f)return;f.onsubmit=e=>{e.preventDefault();const d={name:val("leadName"),phone:val("leadPhone"),car:val("leadCar"),model:val("leadModel"),year:val("leadYear"),country:val("leadCountry"),service:val("leadService"),note:val("leadNote")};const text=["طلب جديد من موقع الخوارزمي","","الاسم: "+d.name,"الهاتف: "+d.phone,"السيارة: "+d.car,"الموديل: "+d.model,"سنة الصنع: "+d.year,"البلد: "+d.country,"الخدمة: "+d.service,"ملاحظات: "+d.note].join("\n");window.open("https://wa.me/201003299254?text="+encodeURIComponent(text),"_blank");const m=document.getElementById("leadMsg");if(m)m.textContent="تم تجهيز رسالة واتساب للتواصل السريع."}}
function val(id){return document.getElementById(id)?.value.trim()||""}
function apiGet(params){return new Promise((resolve,reject)=>{const cb="khCallback_"+Date.now()+Math.floor(Math.random()*100000),s=document.createElement("script"),u=new URL(DEFAULT_API);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set("callback",cb);const tm=setTimeout(()=>{clean();reject(new Error("timeout"))},15000);window[cb]=d=>{clearTimeout(tm);clean();resolve(d)};s.onerror=()=>{clearTimeout(tm);clean();reject(new Error("network"))};function clean(){delete window[cb];s.remove()}s.src=u;s.async=true;document.body.appendChild(s)})}
async function showTrack(code){const t=document.getElementById("trackResult");if(!t)return;if(!code){t.innerHTML='<div class="notice">اكتب رقم الشحنة أولًا.</div>';return}t.innerHTML='<div class="notice">جاري البحث...</div>';try{renderTrack(await apiGet({action:"get",code}),t)}catch(e){t.innerHTML='<div class="notice">تعذر الاتصال بنظام المتابعة. حاول مرة أخرى.</div>'}}
function renderTrack(d,t){if(!d||!d.ok){t.innerHTML='<div class="notice">لم يتم العثور على الشحنة. تأكد من رقم الشحنة.</div>';return}const c=Number(d.statusIndex||0);let h='<div class="card"><h3>'+esc(d.code||"")+'</h3><p><b>العميل:</b> '+esc(d.clientName||"—")+'<br><b>السيارة:</b> '+esc(d.carInfo||"—")+'</p>';statuses.forEach((s,i)=>h+='<div class="step '+(i<=c?"done":"")+'"><span class="dot"></span><div><strong>'+(i+1)+". "+s+'</strong>'+(i===c?'<div class="small">آخر مرحلة مسجلة</div>':"")+'</div></div>');if(d.note)h+='<div class="notice">'+esc(d.note)+'</div>';if(d.updatedAt)h+='<div class="small">آخر تحديث: '+esc(d.updatedAt)+'</div>';t.innerHTML=h+'</div>'}
async function saveTrackingCar(){const m=document.getElementById("adminMsg");if(!m)return;const code=val("carCode"),key=val("adminKey");if(!code||!key){m.innerHTML='<div class="notice">اكتب رقم الشحنة ومفتاح الإدارة.</div>';return}m.innerHTML='<div class="notice">جاري الحفظ...</div>';try{const d=await apiGet({action:"save",key,code,clientName:val("clientName"),phone:val("clientPhone"),carInfo:val("carInfo"),chassis:val("chassis"),statusIndex:document.getElementById("carStatus")?.value||"0",note:val("carNote")});m.innerHTML='<div class="notice">'+esc(d.message||"تم الحفظ")+'</div>'}catch(e){m.innerHTML='<div class="notice">تعذر حفظ الشحنة.</div>'}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
