const API="https://script.google.com/macros/s/AKfycbwRXtdjZYyrKrJC8DBiRvL7AoXNYKVeMuTlygWP0tFPGIdguqzLIWaz7GESIG3vZqh7/exec";
const STATUSES=["تم استلام المستندات","جاري مراجعة المستندات","تم التسجيل المسبق للشحنة (ACID)","تم إنهاء الإجراءات","تم شحن السيارة","وصلت ميناء سفاجا","جاري التخليص الجمركي","تم إنهاء الفحص","تم الإفراج عن السيارة","خرجت من الميناء","تم التسليم"];

document.addEventListener("DOMContentLoaded",()=>{
 const y=document.getElementById("year");if(y)y.textContent=new Date().getFullYear();
 const btn=document.getElementById("menuBtn"),nav=document.getElementById("mainNav");
 if(btn&&nav){btn.onclick=()=>{const open=nav.classList.toggle("open");btn.setAttribute("aria-expanded",String(open));btn.textContent=open?"×":"☰"};nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{nav.classList.remove("open");btn.setAttribute("aria-expanded","false");btn.textContent="☰"}));document.addEventListener("click",e=>{if(nav.classList.contains("open")&&!nav.contains(e.target)&&e.target!==btn){nav.classList.remove("open");btn.setAttribute("aria-expanded","false");btn.textContent="☰"}})}
 const form=document.getElementById("leadForm");
 if(form)form.onsubmit=e=>{e.preventDefault();const d={name:v("leadName"),phone:v("leadPhone"),car:v("leadCar"),model:v("leadModel"),year:v("leadYear"),country:v("leadCountry"),service:v("leadService"),note:v("leadNote")};const text=["طلب جديد من موقع الخوارزمي","",`الاسم: ${d.name}`,`الهاتف: ${d.phone}`,`السيارة: ${d.car||"—"}`,`الموديل: ${d.model||"—"}`,`سنة الصنع: ${d.year||"—"}`,`البلد: ${d.country||"—"}`,`الخدمة: ${d.service||"غير محددة"}`,`ملاحظات: ${d.note||"لا يوجد"}`].join("\n");window.open("https://wa.me/201003299254?text="+encodeURIComponent(text),"_blank","noopener");const m=document.getElementById("leadMsg");if(m)m.textContent="تم تجهيز رسالة واتساب للتواصل السريع."};
 const tf=document.getElementById("trackForm");if(tf)tf.onsubmit=e=>{e.preventDefault();track(v("trackCode"))};
 const ci=document.getElementById("trackCode");if(ci)ci.addEventListener("input",()=>ci.value=ci.value.toUpperCase());
 const top=document.getElementById("topBtn");window.addEventListener("scroll",()=>{if(top)top.classList.toggle("show",window.scrollY>500)});if(top)top.onclick=()=>window.scrollTo({top:0,behavior:"smooth"});
 const tf2=document.getElementById("fullTrackForm");if(tf2)tf2.onsubmit=e=>{e.preventDefault();fullTrack(v("fullTrackCode"))};
});
function v(id){return document.getElementById(id)?.value.trim()||""}
function api(p){return new Promise((res,rej)=>{const cb="kh_"+Date.now()+"_"+Math.random().toString(36).slice(2),s=document.createElement("script"),u=new URL(API);Object.entries(p).forEach(([k,x])=>u.searchParams.set(k,x));u.searchParams.set("callback",cb);const t=setTimeout(()=>{clean();rej()},15000);window[cb]=d=>{clearTimeout(t);clean();res(d)};s.onerror=()=>{clearTimeout(t);clean();rej()};function clean(){delete window[cb];s.remove()}s.src=u;document.body.appendChild(s)})}
async function track(code){const box=document.getElementById("trackResult");if(!box)return;box.innerHTML='<div class="notice">جاري البحث...</div>';if(!code){box.innerHTML='<div class="notice">اكتب رقم الشحنة أولًا.</div>';return}try{const d=await api({action:"get",code});render(d,box)}catch(x){box.innerHTML='<div class="notice">تعذر الاتصال بنظام المتابعة. حاول مرة أخرى.</div>'}}
async function fullTrack(code){const box=document.getElementById("fullTrackResult");if(!box)return;if(!code){box.innerHTML='<div class="notice">اكتب رقم الشحنة أولًا.</div>';return}box.innerHTML='<div class="notice">جاري البحث...</div>';try{const d=await api({action:"get",code});render(d,box,true)}catch(x){box.innerHTML='<div class="notice">تعذر الاتصال بنظام المتابعة. حاول مرة أخرى.</div>'}}
function render(d,box,full=false){if(!d||!d.ok){box.innerHTML='<div class="notice">لم يتم العثور على الشحنة. تأكد من رقم الشحنة.</div>';return}const cur=Number(d.statusIndex||0);let h=`<div class="card ${full?'result-card':''}"><h3>الشحنة: ${e(d.code||"")}</h3><p><b>العميل:</b> ${e(d.clientName||"—")}<br><b>السيارة:</b> ${e(d.carInfo||"—")}<br><b>آخر تحديث:</b> ${e(d.updatedAt||"—")}</p>`;if(full)h+=`<div class="current"><small>الحالة الحالية</small><b>${e(STATUSES[cur]||STATUSES[0])}</b></div>`;STATUSES.forEach((s,i)=>h+=`<div class="step ${i<=cur?'done':''} ${i===cur?'current':''}"><span class="dot"></span><strong>${i+1}. ${s}</strong><small>${i<cur?'تم':i===cur?'الحالة الحالية':'لم يتم بعد'}</small></div>`);if(d.note)h+=`<div class="notice">${e(d.note)}</div>`;box.innerHTML=h+"</div>"}
function e(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
